# Хинчагов Руслан Артурович
## Допольнительная программа образования - Инженерия ИИ 25-26 ## 
## Группа 3 ##

Домашнее задание 1 - numpy 

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a.shape)
print(type(a))

(4,)
<class 'numpy.ndarray'>


In [10]:
a = np.zeros((3,3,4))
print(a.shape)
print(a.dtype)
print(a)
type(a)

(3, 3, 4)
float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


numpy.ndarray

In [3]:
a = np.array([12,1,3,2,4])
b = np.arange(5)
print(a+b)

[12  2  5  5  8]


In [4]:
a = np.array([1,2,3,3,4,5])
print(a ** 2) 
print(3 ** a) 
print(a % 2) 
print(2 % a) 

[ 1  4  9  9 16 25]
[  3   9  27  27  81 243]
[1 0 1 1 0 1]
[0 0 2 2 2 2]


In [5]:
a = 4 * np.ones((2,3))
print(a)

[[4. 4. 4.]
 [4. 4. 4.]]


In [6]:
a = np.array([23.4,4.232,3.52300001,31.52,2.0])
print(np.round(a))

[23.  4.  4. 32.  2.]


In [7]:
b = np.array(np.random.randint(1,10, 16).reshape((4,4)))
b
b1, b2 = np.hsplit(b,2)
b_new = np.hstack((b1.T,b2.T))
print(b)
print(b1)
print(b2)
print(b_new) 
#чуть-чуть попробовал hsplit,hstack, и transpose

[[6 3 5 7]
 [2 1 3 4]
 [5 2 1 1]
 [6 2 5 3]]
[[6 3]
 [2 1]
 [5 2]
 [6 2]]
[[5 7]
 [3 4]
 [1 1]
 [5 3]]
[[6 2 5 6 5 3 1 5]
 [3 1 2 2 7 4 1 3]]


In [9]:
#поменяем местами две строки в матрице 
matrix = np.array(np.random.randint(1,10,(2,3)));
matrix_swapped = matrix[: : -1] #срезом меняем строки местами [: :] - берем все строки и столбцы, а потом с помощью шага -1, меняем строки местами
print(matrix) 
print(matrix_swapped)

[[5 4 8]
 [7 6 5]]
[[7 6 5]
 [5 4 8]]
