# Хинчагов Руслан Артурович
## Допольнительная программа образования - Инженерия ИИ 25-26 ## 
## Группа 3 ##

Домашнее задание 1 - numpy 

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a.shape)
print(type(a))

(4,)
<class 'numpy.ndarray'>


In [2]:
a = np.zeros((3,3,4))
print(a.shape)
print(a.dtype)
print(a)
type(a)

(3, 3, 4)
float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


numpy.ndarray

In [3]:
a = np.array([12,1,3,2,4])
b = np.arange(5)
print(a+b)

[12  2  5  5  8]


In [4]:
a = np.array([1,2,3,3,4,5])
print(a ** 2) 
print(3 ** a) 
print(a % 2) 
print(2 % a) 

[ 1  4  9  9 16 25]
[  3   9  27  27  81 243]
[1 0 1 1 0 1]
[0 0 2 2 2 2]


In [5]:
a = 4 * np.ones((2,3))
print(a)

[[4. 4. 4.]
 [4. 4. 4.]]


In [6]:
a = np.array([23.4,4.232,3.52300001,31.52,2.0])
print(np.round(a))

[23.  4.  4. 32.  2.]


In [7]:
b = np.array(np.random.randint(1,10, 16).reshape((4,4)))
b
b1, b2 = np.hsplit(b,2)
b_new = np.hstack((b1.T,b2.T))
print(b)
print(b1)
print(b2)
print(b_new) 
#чуть-чуть попробовал hsplit,hstack, и transpose

[[9 8 7 3]
 [2 6 1 4]
 [8 7 8 4]
 [8 5 1 8]]
[[9 8]
 [2 6]
 [8 7]
 [8 5]]
[[7 3]
 [1 4]
 [8 4]
 [1 8]]
[[9 2 8 8 7 1 8 1]
 [8 6 7 5 3 4 4 8]]


In [8]:
#поменяем местами две строки в матрице 
matrix = np.array(np.random.randint(1,10,(2,3)));
matrix_swapped = matrix[: : -1] #срезом меняем строки местами [: :] - берем все строки и столбцы, а потом с помощью шага -1, меняем строки местами
print(matrix) 
print(matrix_swapped)

[[2 9 2]
 [6 2 2]]
[[6 2 2]
 [2 9 2]]


In [25]:
print(matrix.sum()) #выведем суму всех чисел матрицы
print(matrix.mean()) #выведем среднее значение матрицы
print(matrix.min()) #минимальное число из всей матрицы
print(matrix[0].min()) #выведем мин значение 1 строки
print(matrix[1].max()) #выведем максимальное значение из 2 строки
print(matrix[1].mean()) #выведем среднее значение 2 строки

23
3.8333333333333335
2
2
6
3.3333333333333335
